version: '3.7'
volumes:
  logs:
    driver: local

services:
  slim:
    # image: php:8-alpine
    # working_dir: /var/www
    command: php -S 0.0.0.0:8000 -t public
    # environment:
    #   docker: "true"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    volumes:
      - .:/var/www
      - logs:/var/www/logs
    networks:
      - app-network
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: main_db
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    ports:
      - '8000:80'
    networks:
      - app-network
networks:
  app-network:
# version: '3.8'
# services:
#   php:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '80:80'
#     volumes:
#       - .:/var/www/html
#       - ./php.ini:/usr/local/etc/php/conf.d/custom-php.ini
#     networks:
#       - app-network
#
